<?php
$title = ___("FAQ");
$this->setLayout('member/layout.phtml');
?>
<div class="am-block">
<ul>
<?php foreach ($categories as $cat) : ?>
    <?php if ($cat == $catActive) : ?>
        <li><h2><?php p($cat) ?></h2></li>
    <?php else: ?>
        <li><h2><a href="<?php echo REL_ROOT_URL ?>/helpdesk/faq/c/<?php echo urlencode($cat) ?>"><?php p($cat) ?></a></h2></li>
    <?php endif; ?>
<?php endforeach; ?>
</ul>
</div>

<ul class="am-helpdesk-faq-list">
<?php foreach ($faq as $f) : ?>
    <li><a href="<?php echo REL_ROOT_URL ?>/helpdesk/faq/i/<?php echo urlencode($f->title) ?>"><?php p($f->title) ?></a></li>
<?php endforeach; ?>
</ul>