<form method="post" name="upgrade" action="<?php p(REL_ROOT_URL)?>/member/upgrade">
<?php $checked = 'checked="checked"'; foreach ($item->_upgrades as $upgrade): $id = rand(10,999999); ?>
    <label for="<?php echo $id?>">
    <input type="radio" <?php echo $checked; $checked ='';?> 
           id="<?php echo $id?>" name="upgrade" value="<?php echo $upgrade->product_upgrade_id ?>" />
        <?php echo $upgrade->getToProduct()->defaultRender($upgrade->getToPlan()) ?>
        <br />
    </label>
<?php endforeach ?>
<input type="hidden" name="invoice_id" value="<?php echo $invoice->public_id ?>" />
<input type="hidden" name="invoice_item_id" value="<?php echo $item->invoice_item_id ?>" />
<div style="margin: 0px auto; width: 50%;">
<input type="submit" class="upgrade-subscription-yes" value="<?php __e('Upgrade Subscription')?>" />
<input type="button" class="popup-close upgrade-subscription-no" value="<?php __e('Cancel')?>" />
</div>
</form>